{% set name = "openlibm" %}
{% set version = "0.6.0" %}
{% set sha256 = "d45439093d1fd15e2ac3acf69955e462401c7a160d3330256cb4a86c51bdae28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/JuliaLang/openlibm/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-no-CC-override.patch

build:
  number: 1001
  skip: true  # [vc<14]

requirements:
  build:
    - {{ compiler("c") }}  # [not win]
    - {{ compiler("m2w64_c") }}  # [win]
  host:

test:
  requires:  # [win]
    - {{ compiler("c") }}  # [win]
  files:  # [win]
    - test_openlibm_win.c  # [win]
  commands:
    - test -d "${PREFIX}/include/openlibm"                            # [unix]
    - test -f "${PREFIX}/lib/libopenlibm.a"                           # [unix]
    - test -f "${PREFIX}/lib/libopenlibm${SHLIB_EXT}"                 # [unix]
    - echo on  # [win]
    - cl /Tc test_openlibm_win.c /I %CONDA_PREFIX%\Library\include\openlibm /link /LIBPATH:"%CONDA_PREFIX%\Library\lib" libopenlibm_static.lib /out:test_openlibm_win.exe  # [win]
    - test_openlibm_win.exe  # [win]

about:
  home: http://openlibm.org/
  license: MIT, ISC, BSD 2-Clause
  license_file: LICENSE.md
  summary: "High quality system independent, portable, open source libm implementation"
  dev_url: https://github.com/JuliaLang/openlibm

extra:
  recipe-maintainers:
    - dfornika
    - jakirkham
    - SylvainCorlay
